### ISSUE TITLE
无语中

### ISSUE THREAD

**Issue by tm2018** [lanyulei/fiy#3]
大佬是认真的吗？没得部署文档，我好不容易用docker-compose部署完成，打开一看是个博客----
![image](https://user-images.githubusercontent.com/31844089/125399339-053e9180-e3e3-11eb-8863-98456d0d1d08.png)

**Comment by firstep** [comment]
哈哈哈，和你一样，go build后，跑起来打开网页都懵逼了。
看了下，把配置好https://github.com/lanyulei/fiy-ui跑起来就行了。
实在强迫症可以把app/admin/apis/system/index.go中的iframe的URL改为fiy-ui的URL

**Comment by lanyulei** [comment]
部署文档，https://www.fdevops.com/2022/04/16/go-cmdb-31077
