### ISSUE TITLE
修改资源数据，提示"参数绑定失败, error: InfoName为必填字段"

### ISSUE THREAD

**Issue by kevinniu666** [lanyulei/fiy#5]
重现步骤:
1. 点击 "资源管理"->"资源"->"资源目录" -> 云主机
2. 选择其中一条数据，修改"外网IP"字段的值，点击保存
3. 抱如下错误
![image](https://user-images.githubusercontent.com/31185341/127115789-637094a6-2655-4ff5-981c-986264bdc8ef.png)

另外自己创建的模型，编辑实例的内容也会出现这个问题，新增没有这样的问题。

**Comment by kevinniu666** [comment]
应该是前端没有传info_name这个参数过来，自己添加了一下这个参数，更新可以成功。前端的代码需要在
render-model组件里面，对edit操作，添加info_name参数
              editData(this.fieldData.id, {
                info_id: this.fieldData.info_id,
                info_name: this.modelName,
                uuid: this.fieldData.uuid,

**Comment by zhangchangwei** [comment]
您好，请问数据结构您是怎么生成的，源码中似乎没有提供相对应SQL文件

**Comment by kevinniu666** [comment]
你需要先把项目的settings文件配置好，路径在config/settings.yml, 然后执行migrate操作。比如我打包出来的二进制文件名称是main

**Comment by lanyulei** [comment]
已修复。

**Comment by Arrowarcher** [comment]
这个还没修复呀，我又遇到了，最新的代码，一模一样。录入的主机里编辑，点保存就报infoName必填 @lanyulei
